apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - secrets.yaml

patches:
  - target:
      kind: SecretProviderClass
      name: grafana-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "612d901f-7d73-45c9-a897-a1da8e7e3fe8"
      - op: replace
        path: /spec/parameters/tenantId
        value: "480dcc85-c1a6-45ad-b7f9-d4b3e55c16f4"

configMapGenerator:
  - name: kube-prometheus-stack-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
